import Link from 'next/link';
import AccountHeader from '@/partials/Headers/AccountHeader';
import Container from '@/ui/container';
import SavedSVG from '@/icons/saved.svg';
import SearchSVG from '@/icons/search.svg';
import ProfileSVG from '@/icons/profile.svg';

//import '@radix-ui/themes/styles.css';

// import '@/styles/normalize.css';
//import '@/styles/reset.css';
import '@/styles/global.scss';
import './layout.scss';
import Card from '@/ui/card';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

export default function RootLayout({ children }) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body>
        <AccountHeader />

        <Container>
          <div className='sidebar-wrapper'>
            <div className='sidebar-wrapper-menu'>
              <nav className='sidebar-menu'>
                <div className='sidebar-menu-profile'>
                  <img src='https://yt3.googleusercontent.com/_QV_qOGwM_-FU-CoEKS3MWuw8N3mSCkbWRRFnftfu09QOATmATZFE-qmjHIFqCtY0MGbJ-w7lg=s900-c-k-c0x00ffffff-no-rj' />
                  <div className='sidebar-menu-profile-info'>
                    <p className='fullname'>Mustafa Zenbil</p>
                    <p className='username'>@zenbil61</p>
                  </div>
                </div>
                <br />
                <Link className='sidebar-menu-item' href='/account/profile'>
                  Profilim
                </Link>
                <Link className='sidebar-menu-item' href='/account/my-contents'>
                  İçeriklerim
                </Link>

                <Link className='sidebar-menu-item' href='/account/new-content'>
                  Yeni İçerik
                </Link>

                <Link className='sidebar-menu-item' href='/account/settings'>
                  Ayarlar
                </Link>
              </nav>
            </div>
            <div className='sidebar-wrapper-content'>{children}</div>
          </div>
        </Container>
      </body>
    </html>
  );
}
